/**
 * Regenerates public/_redirects: a 301 from every reversed comparison URL
 * (b-vs-a) to its canonical form (a-vs-b). Runs as npm prebuild.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';

const dir = join(import.meta.dirname, '..', 'src', 'content', 'comparisons');
const lines = ['# AUTO-GENERATED by scripts/gen-redirects.ts — do not edit by hand.'];

for (const file of readdirSync(dir).filter((f) => f.endsWith('.yaml')).sort()) {
  const { a, b } = parse(readFileSync(join(dir, file), 'utf8'));
  lines.push(`/${b}-vs-${a} /${a}-vs-${b} 301`);
}

writeFileSync(join(import.meta.dirname, '..', 'public', '_redirects'), lines.join('\n') + '\n');
console.log(`gen-redirects: wrote ${lines.length - 1} reversed-comparison redirects`);
